//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactClass.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class imenikEntities : DbContext
    {
        public imenikEntities()
            : base("name=imenikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adresar> Adresar { get; set; }
        public DbSet<vela_view> vela_view { get; set; }
    
        public virtual int Adresar_delete_row(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Adresar_delete_row", iDParameter);
        }
    
        public virtual int Adresar_insert(string name, string lastName, string phoneNumber)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Adresar_insert", nameParameter, lastNameParameter, phoneNumberParameter);
        }
    
        public virtual ObjectResult<Adresar_selectAll_Result> Adresar_selectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Adresar_selectAll_Result>("Adresar_selectAll");
        }
    }
}
